In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("WorldCupMatches.csv")

In [4]:
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [5]:
df.shape

(4572, 20)

In [6]:
df = df.dropna(how="all")

In [7]:
df.shape

(852, 20)

In [8]:
text_cols = df.select_dtypes(include="object").columns
df[text_cols] = df[text_cols].apply(lambda col: col.str.strip())

In [9]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [10]:
df = df.drop(columns=[
    "Win conditions",
    "Referee",
    "Assistant 1",
    "Assistant 2"
])

In [11]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name', 'Attendance',
       'Half-time Home Goals', 'Half-time Away Goals', 'RoundID', 'MatchID',
       'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [12]:
df["Datetime"] = df["Datetime"].str.replace(" - ", " ", regex=False)
df["Datetime"] = pd.to_datetime(df["Datetime"], errors="coerce")

In [13]:
df["Date"] = df["Datetime"].dt.date
df["Time"] = df["Datetime"].dt.time

In [14]:
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID,Home Team Initials,Away Team Initials,Date,Time
0,1930.0,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,4444.0,3.0,0.0,201.0,1096.0,FRA,MEX,1930-07-13,15:00:00
1,1930.0,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,18346.0,2.0,0.0,201.0,1090.0,USA,BEL,1930-07-13,15:00:00
2,1930.0,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,24059.0,2.0,0.0,201.0,1093.0,YUG,BRA,1930-07-14,12:45:00
3,1930.0,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,2549.0,1.0,0.0,201.0,1098.0,ROU,PER,1930-07-14,14:50:00
4,1930.0,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,23409.0,0.0,0.0,201.0,1085.0,ARG,FRA,1930-07-15,16:00:00

In [15]:
df = df.drop(columns=[
    "Datetime",
])

In [16]:
df.head()

,Year,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID,Home Team Initials,Away Team Initials,Date,Time
0,1930.0,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,4444.0,3.0,0.0,201.0,1096.0,FRA,MEX,1930-07-13,15:00:00
1,1930.0,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,18346.0,2.0,0.0,201.0,1090.0,USA,BEL,1930-07-13,15:00:00
2,1930.0,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,24059.0,2.0,0.0,201.0,1093.0,YUG,BRA,1930-07-14,12:45:00
3,1930.0,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,2549.0,1.0,0.0,201.0,1098.0,ROU,PER,1930-07-14,14:50:00
4,1930.0,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,23409.0,0.0,0.0,201.0,1085.0,ARG,FRA,1930-07-15,16:00:00

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 852 entries, 0 to 851
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Stage                 852 non-null    object
 2   Stadium               852 non-null    object
 3   City                  852 non-null    object
 4   Home Team Name        852 non-null    object
 5   Home Team Goals       852 non-null    float64
 6   Away Team Goals       852 non-null    float64
 7   Away Team Name        852 non-null    object
 8   Attendance            850 non-null    float64
 9   Half-time Home Goals  852 non-null    float64
 10  Half-time Away Goals  852 non-null    float64
 11  RoundID               852 non-null    float64
 12  MatchID               852 non-null    float64
 13  Home Team Initials    852 non-null    object
 14  Away Team Initials    852 non-null    object
 15  Date                  842 non-null    object
 16  Time                  842 non-null    object
dtypes: float64(8), object(9)
memory usage: 119.8+ KB

In [18]:
df.isnull().sum()

Year                     0
Stage                    0
Stadium                  0
City                     0
Home Team Name           0
Home Team Goals          0
Away Team Goals          0
Away Team Name           0
Attendance               2
Half-time Home Goals     0
Half-time Away Goals     0
RoundID                  0
MatchID                  0
Home Team Initials       0
Away Team Initials       0
Date                    10
Time                    10
dtype: int64

In [19]:
df.to_csv("WorldCupMatches_cleaned.csv", index=False)