In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("WorldCupPlayers.csv")

In [3]:
df.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [4]:
df = df.dropna(how="all")

In [5]:
df = df.drop_duplicates()

In [6]:
text_cols = df.select_dtypes(include="object").columns
df[text_cols] = df[text_cols].apply(lambda col: col.str.strip())

In [7]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [8]:
df.columns

Index(['roundid', 'matchid', 'team_initials', 'coach_name', 'line-up',
       'shirt_number', 'player_name', 'position', 'event'],
      dtype='object')

In [9]:
df = df.drop(columns=[
    "Line-up",
    "Shirt Number",
    "Position",
    "Event"
])

KeyError: "['Line-up', 'Shirt Number', 'Position', 'Event'] not found in axis"

In [10]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_").str.replace("-", "_")

df = df.drop(columns=[
    "line_up",
    "shirt_number",
    "position",
    "event"
], errors="ignore")

In [11]:
df.head()

   roundid  matchid team_initials           coach_name       player_name
0      201     1096           FRA  CAUDRON Raoul (FRA)       Alex THEPOT
1      201     1096           MEX     LUQUE Juan (MEX)   Oscar BONFIGLIO
2      201     1096           FRA  CAUDRON Raoul (FRA)  Marcel LANGILLER
3      201     1096           MEX     LUQUE Juan (MEX)      Juan CARRENO
4      201     1096           FRA  CAUDRON Raoul (FRA)   Ernest LIBERATI

In [12]:
df.insert(0, "player_id", range(1, len(df) + 1))

In [13]:
df.head()

,player_id,roundid,matchid,team_initials,coach_name,player_name
0,1,201,1096,FRA,CAUDRON Raoul (FRA),Alex THEPOT
1,2,201,1096,MEX,LUQUE Juan (MEX),Oscar BONFIGLIO
2,3,201,1096,FRA,CAUDRON Raoul (FRA),Marcel LANGILLER
3,4,201,1096,MEX,LUQUE Juan (MEX),Juan CARRENO
4,5,201,1096,FRA,CAUDRON Raoul (FRA),Ernest LIBERATI

In [14]:
df.to_csv("WorldCupPlayers_cleaned.csv", index=False)